### ISSUE TITLE
Error  during evaluation 

### ISSUE THREAD

**Issue by aamna2401** [GXYM/TextBPN#6]
I would appreciate your support in reproducing your results. I am trying, but I get zero true positive and zero average precision. Here is a screenshot. 

![Screenshot from 2023-01-21 04-09-36](https://user-images.githubusercontent.com/66481778/213821664-f2424701-8b10-4098-b459-19f41d70b88c.png)

**Comment by GXYM** [comment]
According to the prompt, the model seems to have detected nothing on the image. To solve this problem, you need to first visualize the output of the network to determine whether the text is detected. If not, you should analyze why not. Normally, any text in the picture should be detected. In addition, it is necessary to determine whether it is detected but filtered. In this case, it is necessary to adjust the parameters related to filtering. If it is detected, there is a problem in saving the detection results.发自我的荣耀手机-------- 原始邮件 --------发件人： Aamna Khan ***@***.***>日期： 2023年1月21日周六 07:15收件人： GXYM/TextBPN ***@***.***>抄送： Subscribed ***@***.***>主    题： [GXYM/TextBPN] Error in during evaluation  (Issue #6)
I would appreciate your support in reproducing your results. I am trying, but I get zero true positive and zero average precision. Here is a screenshot.

**Comment by GXYM** [comment]
If you use DCN, make sure to compile cuda files correctly, otherwise there will be no output from the network, which will also cause this problem in the evaluation.发自我的荣耀手机-------- 原始邮件 --------发件人： Aamna Khan ***@***.***>日期： 2023年1月21日周六 07:15收件人： GXYM/TextBPN ***@***.***>抄送： Subscribed ***@***.***>主    题： [GXYM/TextBPN] Error in during evaluation  (Issue #6)
I would appreciate your support in reproducing your results. I am trying, but I get zero true positive and zero average precision. Here is a screenshot.

**Comment by GXYM** [comment]
It is recommended that you pay attention to our textbpn++, which is an upgraded version of textbpn, and we have fixed many bugs, making it easier to reproduce.发自我的荣耀手机-------- 原始邮件 --------发件人： Aamna Khan ***@***.***>日期： 2023年1月21日周六 07:15收件人： GXYM/TextBPN ***@***.***>抄送： Subscribed ***@***.***>主    题： [GXYM/TextBPN] Error in during evaluation  (Issue #6)
I would appreciate your support in reproducing your results. I am trying, but I get zero true positive and zero average precision. Here is a screenshot.

**Comment by aamna2401** [comment]
When I studied in depth I found interest gives zero area. 
![error](https://user-images.githubusercontent.com/66481778/213849922-092fd6a2-360f-4ed5-93f3-e3409f199dfd.png)

**Comment by aamna2401** [comment]
couldn't solve this yet.

**Comment by GXYM** [comment]
> couldn't solve this yet.

You should first visualize the output of the network, ensure that there is a detected profile, and then evaluate it. If text is detected on the image, the area should not be 0 when the evaluation occurring.
